name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'     
        required: true
        default: 'auto' 
        type: choice
        options:
          - minor
          - patch 
      repository:
        description: Repository (in owner/repo format)
        required: true
        default: leandroberetta/helm-charts
        type: string
      release_branch:
        description: Branch to release
        required: true
        default: master
        type: string
  
jobs:
  initialize:
    name: Initialize
    runs-on: ubuntu-20.04
    outputs:
      current_version: ${{ steps.current_version.outputs.current_version }}
      releasing_version: ${{ steps.releasing_version.outputs.releasing_version }}
      branch_version: v${{ steps.version_branch.outputs.version_branch }}
      next_version: ${{ steps.next_version.outputs.next_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.repository }}
          ref: ${{ github.event.inputs.releasing_branch }}       
      
      - name: Determine release version
        id: release_version
        run: |
          RAW_VERSION=$(sed -rn 's/^VERSION \?= v(.*)/\1/p' Makefile)
          
          # Remove any pre release identifier (ie: "-SNAPSHOT")
          RELEASE_VERSION=$(./.github/workflows/util/semver bump release $RAW_VERSION)
          
          if [[ $RELEASE_TYPE == "patch" ]]
          then
              RELEASE_VERSION=v$(./.github/workflows/util/semver bump $RELEASE_TYPE $RELEASE_VERSION)
          fi

          echo "::set-output name=release_version::$RELEASE_VERSION"      
      - name: Determine next version
        env:
          RELEASE_TYPE: ${{ github.event.inputs.release_type }}
          RELEASE_VERSION: ${{ steps.release_version.outputs.release_version }}
        id: next_version
        run: |
          if [[ $RELEASE_TYPE == "patch" ]]
          then
              NEXT_VERSION=v$(./.github/workflows/util/semver bump $RELEASE_TYPE $RELEASE_VERSION)
          elif [[ $RELEASE_TYPE == "minor" ]]
          then 
              NEXT_VERSION=v$(./.github/workflows/util/semver bump minor $RELEASE_VERSION)          
          fi

          echo "::set-output name=releasing_version::$NEXT_VERSION"
              
      - name: Log information
        run: |         
          echo "Release version: ${{ steps.release_version.outputs.release_version }}"
                   
          echo "Next version: ${{ steps.next_version.outputs.next_version }}"

  release:
    name: Release
    runs-on: ubuntu-20.04
    needs: [initialize]
    env:
      RELEASE_TYPE: ${{ needs.initialize.outputs.release_type }}      
      RELEASE_VERSION: ${{ needs.initialize.outputs.release_version }}
      NEXT_VERSION: ${{ needs.initialize.outputs.next_version }}      
      RELEASE_BRANCH: ${{ github.event.inputs.release_branch }}
      GH_PULL_URI: https://api.github.com/repos/${{ github.event.inputs.repository }}/pulls
      Gh_RELEASE_URI: https://api.github.com/repos/${{ github.event.inputs.repository }}/releases
    steps:    
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.repository }}
          ref: ${{ github.event.inputs.releasing_branch }} 
        
      - name: Configure git
        run: |
          git config user.email 'lea.beretta@gmail.com'
        
          git config user.name 'leandroberetta'
 
      
